Repository Survival-DEV/blog-backend, pull requests merged in 2021-06, with the labels that each got.

#8 users table
  package-lock.json
  package.json
  src/app.module.ts
  src/main.ts
  src/users/user.entity.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
Labels: Approved

#12 Blog-6: Create blog table
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
  src/app.module.ts
  src/blogs/blogs.module.ts
  src/blogs/controller/blogs.controller.spec.ts
  src/blogs/controller/blogs.controller.ts
  src/blogs/model/blog.dto.ts
  src/blogs/model/blog.entity.ts
  src/blogs/model/blog.interface.ts
  src/blogs/service/blogs.service.spec.ts
  src/blogs/service/blogs.service.ts
  src/main.ts
  src/users/user.entity.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: Approved

#13 Blog-9: Create category table
  src/app.module.ts
  src/categories/categories.module.ts
  src/categories/controller/categories.controller.spec.ts
  src/categories/controller/categories.controller.ts
  src/categories/model/category.dto.ts
  src/categories/model/category.entity.ts
  src/categories/model/category.interface.ts
  src/categories/service/categories.service.spec.ts
  src/categories/service/categories.service.ts
Labels: Approved

#16 Create tag table
  package-lock.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  src/tags/dto/create-tag.dto.ts
  src/tags/dto/update-tag.dto.ts
  src/tags/entities/tag.entity.ts
  src/tags/tags.controller.spec.ts
  src/tags/tags.controller.ts
  src/tags/tags.module.ts
  src/tags/tags.service.spec.ts
  src/tags/tags.service.ts
  test/app.e2e-spec.ts
Labels: Approved, Database

#19 Blog-1: add issue & PR templates
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/PULL_REQUEST_TEMPLATE/pr_template.md
Labels: awaiting-review

#17 Blog #7 :setup swagger
  package-lock.json
  package.json
  src/blogs/controller/blogs.controller.ts
  src/blogs/model/blog.dto.ts
  src/blogs/model/blog.interface.ts
  src/categories/controller/categories.controller.ts
  src/categories/model/category.dto.ts
  src/main.ts
  src/tags/dto/create-tag.dto.ts
  src/tags/dto/update-tag.dto.ts
  src/tags/tags.controller.ts
  src/users/dto/create-user.dto.ts
  src/users/dto/update-user.dto.ts
  src/users/users.controller.ts
Labels: Approved
